apiVersion: apps/v1
kind: Deployment
metadata:
    name: mud
spec:
    selector:
        matchLabels:
            app: mud
    replicas: 1
    template:
        metadata:
            labels:
                app: mud
        spec:
            containers:
            -   name: mud
                image: gcr.io/kalschi-agones/mud:v4
                imagePullPolicy: Always
                ports:
                    -   name: http
                        containerPort: 80
                ports:
                    -   name: http
                        containerPort: 8080
                livenessProbe:
                    tcpSocket:
                        port: 8080
                    initialDelaySeconds: 180
                # readinessProbe:
                #     httpGet:
                #         port: 8080
                #         path: /ws
                readinessProbe:
                    tcpSocket:
                        port: 8080
                    initialDelaySeconds: 10
                # env:
                #     -   name: PROJECT_ID
                #         value: kalschi-agones
                #     -   name: LOCATION
                #         value: global
                #     -   name: NAMESPACE
                #         valueFrom:
                #             fieldRef:
                #                 fieldPath: metadata.namespace
                #     -   name: CONTAINER
                #         value: "dialogflow-fulfillment"
