kind: Service
apiVersion: v1
metadata:
  name: mud
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  selector:
    app: mud
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
