apiVersion: apps/v1
kind: Deployment
metadata:
    name: mud
spec:
    strategy:
        type: RollingUpdate
        rollingUpdate:
            maxSurge: 1
        #   maxUnavailable: 25%
    selector:
        matchLabels:
            app: mud
    replicas: 1
    template:
        metadata:
            labels:
                app: mud
        spec:
            affinity:
                nodeAffinity:
                  requiredDuringSchedulingIgnoredDuringExecution:
                    nodeSelectorTerms:
                    - matchExpressions:
                      - key: dedicated
                        operator: In
                        values: 
                        - mud
            tolerations:
                - key: dedicated
                  operator: Equal
                  value: mud
                  effect: NoSchedule
            containers:
            -   name: mud
                image: gcr.io/kalschi-agones/mud:gke-v3
                imagePullPolicy: Always
                ports:
                    -   name: ws
                        containerPort: 9999
                livenessProbe:
                    tcpSocket:
                        port: 9999
                    initialDelaySeconds: 30
                readinessProbe:
                    tcpSocket:
                        port: 9999
                    initialDelaySeconds: 30
                resources:
                    requests:
                        cpu: 50m
                        memory: 3.5G   
                env:
                    - name: PROJECT_ID
                      value: kalschi-agones
                    - name: INSTANCE_ID
                      value: game-spanner
                    - name: DATABASE_ID
                      value: mud-sample
                